name: Sync Codes to HF Spaces

on:
  push:
    branches: [main]
  workflow_dispatch: # Enables the manual trigger button

jobs:
  sync-client-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Client Code to Space Cripple-Lee/Auto-Train-Agents-Client
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Cripple-Lee/Auto-Train-Agents-Client
          hf_token: ${{ secrets.HF_TOKEN }}
          subdirectory: 'client'
          space_sdk: 'static'

  sync-server-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Server Code to Space Cripple-Lee/Auto-Train-Agents-Server
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Cripple-Lee/Auto-Train-Agents-Server
          hf_token: ${{ secrets.HF_TOKEN }}
          subdirectory: 'server'
          space_sdk: 'docker'
